title: nukapi - Software und Service
baseURL: /
params:
  palette: blue
  header:
    title: nukapi
    logo_img: /images/untitled.png
    has_nav: true
    menu:
      actions:
        - label: Sign Up
          url: /signup
  footer:
    subscribe_title: Subscribe
    subscribe_content: Stay up to date with our latest developments.
    has_subscribe: true
    social_title: Community
    tagline: SaaS theme by Stackbit
    logo_img: /images/untitled.png
    has_social: true
    content: "&copy; Stackbit. All rights reserved."
    links:
      - text: Made with Stackbit
        url: https://www.stackbit.com
        new_window: true
    nav_title: Company
    has_nav: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
